---
title: "interprétation corrélation négative sur le broad scale alors qu'elle est positive sur le medium scale."
output: html_notebook
---

interprétation corrélation négative sur le broad scale alors qu'elle est positive sur le medium scale.

=> 
exemple d'explication du changement de signe de la richesse entre le modèle purement socioeco et le broad scale

modèle purement socioéconomique 
taux de possession de véhicule
95 % = 0.5 de densité et    10 000 euros de revenu médian : bord de mer
90 % = 0.5 de densité  et    8 000 euros de revenu médian : classe moyenne
85 % = 0.5 de densité  et    6 000 euros de revenu médian : Gilet Jaune

87 % = 1.2 de densité et  10 000 euros de revenu médian  : centre ville
86 % = 1   de densité et    7 000 euros de revenu médian : proche centre
85 %  = 0.8 de densité et   4 000 euros de revenu médian : quartier

= effet positif de la richesse au niveau global


broad scale 

91 % = 0.5 de densité et 10 000 euros de revenu médian
90 % = 0.5 de densité  et    8 000 euros de revenu médian
89 % = 0.5 de densité  et 6 000 euros de revenu médian

86.5 % = 1.2 de densité et  10 000 euros de revenu médian
86 % = 1   de densité et    7 000 euros de revenu médian
85.5 %  = 0.8 de densité et 4 000 euros de revenu médian

= effet négatif de la richesse qui doit " rattraper l'effet densité en ville "

La longueur d'onde importante de la densité, et peu importante de la revenu médian.


```{r}
donnees_spatiales <- data.frame(
complet = c(100, 95, 90, 35, 30, 10),
broadscale= c(95, 95, 95, 25, 25, 25),
densite = c(0.05, 0.2, 0.4, 3, 3, 3.5),
revenu = c(15000, 8000, 2000, 30000, 15000, 1000))
head(donnees_spatiales)
regcomplet<-lm(complet ~densite+ revenu , data=donnees_spatiales)
print(summary(regcomplet))
regbroadscale<-lm(broadscale ~densite+ revenu , data=donnees_spatiales)
print(summary(regbroadscale))
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
